import json
import os

PROJECT_DIR = os.path.dirname(os.path.dirname(__file__))

IGNITE_ADDRESS = 'IGNITE_ADDRESS'
IGNITE_PORT = 'IGNITE_PORT'
MARIADB_ADDRESS = 'MARIADB_ADDRESS'
RETHINK_ADDRESS = 'RETHINK_ADDRESS'
RETHINK_PORT = 'RETHINK_PORT'
ENV = 'ENV'
CATALOG = 'catalog'
HDFS_ADDRESS = 'HDFS_ADDRESS'
SOURCE_CONNECTIONS = 'SOURCE_CONNECTIONS'
LIMA_COMMONAPI_SVCS_URL = 'LIMA_COMMONAPI_SVCS_URL'
LIMA_TOKEN_URL = 'LIMA_TOKEN_URL'
LIMA_COMMON_URL = 'LIMA_COMMON_URL'
LIMA_TOKEN_GENERATE_URL = 'LIMA_TOKEN_GENERATE_URL'
LIMA_DTF_TFM_URL = 'LIMA_DTF_TFM_URL'
LIMA_IFM_SIDEBAR_URL = 'LIMA_IFM_SIDEBAR_URL'
LIMA_IFM_CONNECTION_INFO_URL = 'LIMA_IFM_CONNECTION_INFO_URL'
RABBITMQ_ADDRESS = "RABBITMQ_ADDRESS"
RABBITMQ_PORT = "RABBITMQ_PORT"
RABBITMQ_USER_NAME = "RABBITMQ_USER_NAME"
RABBITMQ_PASSWORD = "RABBITMQ_PASSWORD"


def json_print(data):
    print(json.dumps(data, indent=4))


def lima_print(s):
    print(s)


def toJson(data):
    return json.dumps(data, indent=4)


def load_json(data):
    return json.loads(data)
